name: Lint Checker

on:
  pull_request:
    branch: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - uses: actions/checkout@v1
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install dependencies
        run: yarn install
      - name: Lint check
        run: yarn lint
        